
const fs = require('fs');
const path = require('path');

try {
  const dataPath = path.join(process.cwd(), 'src', 'temp-data.txt');
  const outputPath = path.join(process.cwd(), 'src', 'lib', 'client-data-array.ts');

  if (!fs.existsSync(dataPath)) {
    console.error('Error: src/temp-data.txt not found. Please create it and paste your data.');
    process.exit(1);
  }

  const data = fs.readFileSync(dataPath, 'utf8');
  const lines = data.split(/\r?\n/);
  const clients = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    const parts = line.split('\t');
    // Trim every part to be safe
    const cleanedParts = parts.map(p => p.trim());
    const [code, name, ...emails] = cleanedParts;

    if (code && name) {
      // Filter out any empty email strings that might result from trailing tabs
      const validEmails = emails.filter(e => e && e.includes('@'));
      
      if (validEmails.length > 0) {
        clients.push({
          code: code, // Already trimmed
          name: name, // Already trimmed
          emails: validEmails
        });
      }
    }
  }

  // Use JSON.stringify to correctly handle all special characters in names and emails
  const clientsJSON = JSON.stringify(clients, null, 2);

  const tsContent = `
// This file is generated by scripts/convert-data.js. Do not edit manually.
export const clients = ${clientsJSON};
  `;

  fs.writeFileSync(outputPath, tsContent);
  
  console.log(`Conversion complete! ${clients.length} clients written to src/lib/client-data-array.ts`);

} catch (error) {
  console.error('An unexpected error occurred during conversion:', error);
  process.exit(1);
}
