const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'src', 'temp-data.txt');
const outputPath = path.join(__dirname, '..', 'src', 'lib', 'client-data-array.ts');

try {
  const data = fs.readFileSync(dataPath, 'utf8');
  const lines = data.split(/\r?\n/);
  const clients = [];

  // Start from row 1 to skip header
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line || !line.trim()) {
      continue; // Skip empty lines
    }

    const parts = line.split('\t');
    const code = parts[0] ? parts[0].trim() : '';
    const name = parts[1] ? parts[1].trim() : '';
    
    if (code && name) {
      const emails = parts.slice(2)
        .map(e => e.trim())
        .filter(e => e && e.includes('@')); // Filter for valid email format

      clients.push({
        code: code,
        name: name,
        emails: emails,
      });
    } else if (line.trim()) {
      console.warn(`[WARN] Skipped malformed line ${i + 1}: ${line}`);
    }
  }

  const tsContent = `// This file is auto-generated by scripts/convert-data.js. Do not edit manually.
export const clients = ${JSON.stringify(clients, null, 2)};
`;

  fs.writeFileSync(outputPath, tsContent);
  console.log(`\n✅ Conversion complete! ${clients.length} clients written to src/lib/client-data-array.ts\n`);

} catch (error) {
  console.error('\n❌ An error occurred during the conversion process:');
  console.error(error);
  process.exit(1);
}
